repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: Check YAML
        types: [yaml]
        stages: [pre-commit, manual]
      - id: end-of-file-fixer
        name: Check end-of-file
        types: [text]
        stages: [pre-commit, manual]
      - id: trailing-whitespace
        name: Fix trailing whitespace
        types: [text]
        stages: [pre-commit, manual]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff
        name: Ruff lint
        types_or: [python, pyi]
        require_serial: true
        stages: [pre-commit, manual]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: Ruff format
        types_or: [python, pyi]
        require_serial: true
        stages: [pre-commit, manual]
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.40.1
    hooks:
      - id: basedpyright
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.14.1-1
    hooks:
      - id: shfmt
        name: Format shell scripts
        types: [shell]
        stages: [pre-commit, manual]
        args: [-w, -i, "4", -s, -bn]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1-1
    hooks:
      - id: shellcheck
        name: Check shell scripts
        types: [shell]
        stages: [pre-commit, manual]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        types: [yaml]
        files: ^\.github/workflows/
        stages: [pre-commit, manual]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        name: TOML format
        types: [file, toml]
        exclude: "schema/examples/invalid"
        stages: [pre-commit, manual]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.3
    hooks:
      - id: markdownlint-cli2
        files: \.(md|qmd)$
        types: [file]
        exclude: LICENSE.md
  - repo: https://github.com/snakemake/snakefmt
    rev: v2.0.3
    hooks:
      - id: snakefmt
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.8.1
    hooks:
      - id: betterleaks
  - repo: local
    hooks:
      - id: lint
        name: Snakemake lint
        language: python
        entry: snakemake --lint text
        additional_dependencies: ["snakemake>=9.1"]
        files: '.*\.smk$'
        pass_filenames: true
