channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jinja2
  - jupyter
  - jupyter-book
  - jsonschema
  - pypandoc
  - r-base
  - r-bookdown
  - r-rmarkdown
  - ruamel.yaml
  - snakemake
