$schema: "http://json-schema.org/draft-07/schema#"

description: |
  NBIS project admin configuration. The configuration file resides in
  the project root directory which will be inferred from the
  configuration file name.

properties:
  project_name:
    description: NBIS project name
    default: nbis-project
    type: string
  confluence:
    description: Confluence configuration.
    type: object
    default: {}
    properties:
      url:
        description: Confluence url.
        type: [string, 'null']
        default: null
  docs:
    description: Documentation configuration
    type: object
    default: {}
    properties:
      src:
        description: Documentation source directory.
        type: string
        default: docs
  webexport:
    description: Webexport configuration
    type: object
    default: {}
    properties:
      url:
        description: |
          Webexport url. All directories located in the docs directory
          will be synced to this url.
        type: [string, 'null']
        default: null
      include:
        description: |
          List of directories, relative to the documentation source
          directory, to include in webexport.
  bibliography:
    description: Bibliography file
    type: string
    default: references/bibliography.bib
