$schema: "http://json-schema.org/draft/2020-12/schema#"

description: |
  NBIS project admin configuration. The configuration file resides in
  the project root directory which will be inferred from the
  configuration file name.

properties:
  project_name:
    description: NBIS project name
    default: nbis-project
    type: str
  confluence:
    description: Confluence configuration. 
    type: object
    default: {}
    properties:
      url:
        description: Confluence url.
        type: [str, 'null']
        default: null
  webexport:
    description: Webexport configuration
    type: object
    default: {}
    properties:
      url:
        description: |
          Webexport url. All files located in the webexport build
          directory will be synced to this url.
        type: [str, 'null']
        default: null
      builddir:
        description: |
          Webexport build directory.
        type: str
        default: reports/webexport
      src:
        description: |
          Webexport source directory.
        type: str
        default: docs/webexport
  bibliography:
    description: Bibliography file
    type: str
    default: references/bibliography.bib
    
