name: CI

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    defaults:
      run:
        shell: bash -l {0} # a login shell is required for conda activation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.13
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest

      - name: Run tox to test installation of project
        run: python -m tox p -e project
