name: CI

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    defaults:
      run:
        shell: bash -l {0} # a login shell is required for conda activation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: cache-conda
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Create Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          # environment-file: conda-linux-64.lock; waiting for conda update
          environment-file: environment.yml
          use-only-tar-bz2: true
          activate-environment: "nbis"

      - name: Echo environment
        run: |
          echo "CONDA_PREFIX: $CONDA_PREFIX"
          conda list
          conda env list

      - name: Install test dependencies
        run: conda install -c conda-forge pytest pip tox pylint

      - name: Install R revealjs
        run: R -e "install.packages('revealjs', repos='https://cran.rstudio.com/')"

      - name: Install nbis-project-admin
        run: pip install --no-deps .

      - name: Run tests
        run: pytest

      - name: Run tox to test installation of project
        run: python -m tox -e project
